### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by syl20lego** [soajs/soajs.utilities#1]
Hi,

I'm trying for the first time soajs and cannot get very far as the installation doesn't seems to be working. 
I hope this is the right project to open the issue.

I get bunch of error but the script continue and give me a message at the end that the container are started like everything looks fine?

My docker installation works fine, I'm able to do  a "docker run -it ubuntu bash" without problem.

Here is the command output:

~  npm install soajs.utilities
soajs.utilities@0.2.2 node_modules/soajs.utilities
└── shelljs@0.6.0
➜  ~ cd node_modules/soajs.utilities
➜  soajs.utilities ls
LICENSE      README.md    data         lib          node_modules package.json
➜  soajs.utilities cd lib
➜  lib ./dockerDeploy.sh
Initializing and checking prerequisites ...
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

1- Cleaning previous docker containers ...
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
docker: "stop" requires a minimum of 1 argument.
See 'docker stop --help'.

Usage:  docker stop [OPTIONS] CONTAINER [CONTAINER...]

Stop a running container.
Sending SIGTERM and then SIGKILL after a grace period
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
docker: "rm" requires a minimum of 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers

---

2- Starging Mongo Container "soajsData" ...
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.

---

Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Mongo ip is:

3- Starging Mongo Container "soajsDataDev" ...
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.

---

Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Mongo Dev ip is:

4- Importing core provisioned data ...
About to run: mongo --host DOCKER /Users/slegaul1/node_modules/soajs.utilities/lib/../data/provision/data-tmp.js
/Users/slegaul1/node_modules/soajs.utilities/data/provision /Users/slegaul1/node_modules/soajs.utilities/lib
MongoDB shell version: 3.2.4
connecting to: DOCKER:27017/test
2016-04-17T10:24:58.079-0400 I NETWORK  [thread1] getaddrinfo("DOCKER") failed: nodename nor servname provided, or not known
2016-04-17T10:24:58.081-0400 E QUERY    [thread1] Error: couldn't initialize connection to host DOCKER, address is invalid :
connect@src/mongo/shell/mongo.js:226:14
@(connect):1:6

exception: connect failed
Done importing data:  1
/Users/slegaul1/node_modules/soajs.utilities/lib

5- Importing URAC data...
About to run: mongo --host 127.0.0.1 /Users/slegaul1/node_modules/soajs.utilities/lib/../data/urac/data-tmp.js
/Users/slegaul1/node_modules/soajs.utilities/data/urac /Users/slegaul1/node_modules/soajs.utilities/lib
MongoDB shell version: 3.2.4
connecting to: 127.0.0.1:27017/test
2016-04-17T10:24:58.238-0400 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, reason: errno:61 Connection refused
2016-04-17T10:24:58.238-0400 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
connect@src/mongo/shell/mongo.js:226:14
@(connect):1:6

exception: connect failed
Done importing data:  1
/Users/slegaul1/node_modules/soajs.utilities/lib

---

6- Starting SERVICES ...
- Starting Controller Container soajs.urac ...
  docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
  See 'docker run --help'.
- Starting Controller Container soajs.dashboard ...
  docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
  See 'docker run --help'.
- Starting Controller Container soajs.prx ...
  docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
  See 'docker run --help'.
- Starting Controller Container soajs.controller ...
  docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
  See 'docker run --help'.

---

Cannot connect to the Docker daemon. Is the docker daemon running on this host?

7- Starting NGINX Container "nginx" ...
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.

---

8- Containers created and deployed:
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

---

Cannot connect to the Docker daemon. Is the docker daemon running on this host?

 Add the following to your /etc/hosts file:
      dashboard-api.soajs.org
      dashboard.soajs.org

 Containers started, please login to the dashboard @ http://dashboard.soajs.org

**Comment by keithwbacon** [comment]
Are you using a Mac?  We recommend using the docker-machine install on Mac which requires virtualbox.  https://www.virtualbox.org

Docker-machine on mac requires a default machine, this is will correct this:
eval "$(docker-machine env default)"

http://www.soajs.org/#/documentation/deployment/docker-m-mac

**Comment by syl20lego** [comment]
Thanks for the quick reply,
Mac OSX, El Capitan, 10.11.4
yes, eval "$(docker-machine env default)" fixed the issue.

But in the end there is still something wrong :(
➜  lib docker-machine ls
NAME                 ACTIVE   DRIVER       STATE     URL                         SWARM                         DOCKER    ERRORS
default              \*        virtualbox   Running   tcp://192.168.99.100:2376                                 v1.11.0
soajs-dash           -        virtualbox   Error                                 soajs-swarm-master            Unknown   machine does not exist
soajs-dev            -        virtualbox   Error                                 soajs-swarm-master            Unknown   machine does not exist
soajs-swarm-master   -        virtualbox   Error                                 soajs-swarm-master (master)   Unknown   machine does not exist
soajs-v-keystore     -        virtualbox   Error                                                               Unknown   machine does not exist

**Comment by keithwbacon** [comment]
Please remove all the soajs docker-machines and have docker ready for install:
docker-machine rm -f soajs-dash
docker-machine rm -f soajs-dev
docker-machine rm -f soajs-swarm-master
docker-machine rm -f soajs-v-keystore
 eval "$(docker-machine env default)"

After all machines soajs machines are removed run ./dockermachineDeploy.sh

**Comment by keithwbacon** [comment]
If you do not need your virtualbox VMs:

docker-machine rm -f $(docker-machine ls -q)

or remove each soajs machine one by one:
docker-machine rm -f soajs-dash

After all machines soajs machines are removed run ./dockermachineDeploy.sh

**Comment by syl20lego** [comment]
Thanks working now.
